# Generated by Django 5.2.8 on 2026-09-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_inappropriate',
            field=models.BooleanField(default=False),
        ),
    ]
