# Generated by Django 5.2.8 on 2026-09-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_is_inappropriate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='report_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
